### ISSUE TITLE
Portable RE

### ISSUE THREAD

**Issue by vityok** [massung/re#1]
Hi Jeffrey,

I've refactored the sources a little bit and made the RE regular expressions engine portable.

You can view the sources [here](https://bitbucket.org/vityok/cl-string-match/src/d3a12f0dcff7de7352d312cbea95eca40626c212/src/pre.lisp?at=devel) — this is the latest changest in the devel branch of the cl-string-match repository.

Basically, the most significant change is using CL-YACC instead of defparser to parse the regular expression. Rest of the code required no modifications.

However, a [simple benchmark](https://bitbucket.org/vityok/cl-string-match/src/d3a12f0dcff7de7352d312cbea95eca40626c212/bench/benchmark-re.lisp?at=devel) shows that RE is outperformed by CL-PPCRE (though it is much larger and more complex).

Thanks for your great work!
Victor

**Comment by massung** [comment]
Victor,

Thanks for doing this! I don't think I'll check this into master since I don't use CL-YACC and won't be able to maintain it, but when I get a chance I'll make a branch for CL-YACC support that I'll put this into and make a note of it in the README.

This is actually really nice, because it will allow others to use many of the other libraries I've written (as most of them depend on this one at some fundamental level).

Thanks again!
Jeff

**Comment by vityok** [comment]
Hi Jeffrey,

I am glad that these modifications have such long-lasting consequences (by making other libraries portable).

Meanwhile, given the permissive license conditions RE is included in the cl-string-match as a Portable RE module. Hopefully somebody will find it useful as well.

I am also compiling a [list of all known/existing RE engines in Common Lisp](https://bitbucket.org/vityok/cl-string-match/wiki/Regular_expressions_in_Common_Lisp). Feel free to contribute!

Thanks,
Victor

**Comment by massung** [comment]
Victor,

I've made the cl-yacc branch, and updated the README noting of its existence (and thanking you). If you could, would you modify re.lisp there with your changes and verify them, then create a pull request for that branch? I cannot validate that branch myself (not without downloading cl-yacc, and all of its dependencies, etc). 

It would be very helpful if you could.

Thanks!
Jeff

**Comment by vityok** [comment]
Jeff,

Dealing with Git/GitHub workflow is the most challenging task for me so far. I will try to cope with it tomorrow.

Thanks,
Victor

**Comment by massung** [comment]
I understand. If you don't want to make a pull request, simply get the cl-yacc branch (after a pull do `git checkout cl-yacc`), edit re.lisp appropriately, then just email me the final file that works for you. If you can also edit re.asd to ensure that cl-yacc is a dependency, that would be awesome as well. ;-)

Thanks again,
Jeff

**Comment by vityok** [comment]
Hi Jeff,

I've sent you an e-mail, please check your inbox. Unfortunately Git is too cryptic for me to use it easily.

Thanks for your great work!

Victor

**Comment by massung** [comment]
The re.lisp and re.asd files have been pushed to the cl-yacc branch. Thanks again, Victor. Closing this issue.
